"""
Security-investigation MCP server.

Exposes 5 read-only threat-intelligence tools backed by synthetic data.
data.py queries PostgreSQL (see db/schema.sql and db/seed.sql) via
mcp_server/db.py; this module only defines the tool contracts and never
touches the database directly. These tool names and JSON return shapes
are the stable contract that a downstream agent integrates against and
must not change.

Phase 10: this server is packaged to run inside Docker Compose alongside
its Postgres backend (see ../docker-compose.yml), so it no longer runs
over stdio -- another container can't share a process's stdin/stdout
pipe. It now serves the streamable-http transport bound to 0.0.0.0:8000
(path /mcp), reachable from outside the container at whatever host port
compose maps to it. Tool names, parameters, and return shapes are
unchanged from the stdio version.

Run directly:
    DATABASE_URL=postgresql://... python mcp_server.py
Then connect an MCP client to http://<host>:8000/mcp using the
streamable-http transport.
"""

from mcp.server.fastmcp import FastMCP

import data

mcp = FastMCP("security-investigation-mock", host="0.0.0.0", port=8000)


@mcp.tool()
def lookup_ip_reputation(ip: str) -> dict:
    """Look up threat-intelligence reputation data for a single IP address.

    Args:
        ip: The IP address to look up, e.g. "203.0.113.10".

    Returns exactly this JSON shape:
        {
          "ip": str,                       # echoes the input IP
          "malicious": bool,                # true if any source flags it malicious
          "score": int,                     # 0-100 risk score, higher = worse
          "sources_flagging": list[str],    # e.g. ["VirusTotal", "AbuseIPDB"]
          "first_seen": str | null          # "YYYY-MM-DD", or null if unknown
        }

    An IP not present in the dataset is NOT an error: it returns
    malicious=false, score=0, sources_flagging=[], first_seen=null.
    """
    return data.lookup_ip_reputation(ip)


@mcp.tool()
def geolocate_ip(ip: str) -> dict:
    """Look up coarse geolocation and network ownership data for an IP address.

    Args:
        ip: The IP address to geolocate, e.g. "203.0.113.10".

    Returns exactly this JSON shape:
        {
          "ip": str,              # echoes the input IP
          "found": bool,          # true if geolocation data exists for this IP
          "country": str | null,
          "city": str | null,
          "asn": str | null,      # e.g. "AS64510"
          "org": str | null       # network operator / hosting org name
        }

    An IP not present in the dataset is NOT an error: it returns
    found=false with country/city/asn/org all null.
    """
    return data.geolocate_ip(ip)


@mcp.tool()
def query_logs(src_ip: str, hours: int = 24) -> dict:
    """Query security event logs generated by a given source IP address.

    Args:
        src_ip: The source IP address to filter logs by, e.g. "203.0.113.45".
        hours: How many hours back from now to include (default 24).

    Returns exactly this JSON shape:
        {
          "src_ip": str,     # echoes the input IP
          "hours": int,      # echoes the effective time window used
          "count": int,      # number of matching log entries
          "logs": [
            {
              "id": str,             # e.g. "LOG-0001"
              "timestamp": str,      # ISO 8601 UTC, e.g. "2026-09-18T02:15:00Z"
              "event_type": str,     # one of: failed_login, port_scan,
                                     #         outbound_conn, file_download
              "src": str,            # source IP (matches src_ip)
              "detail": str          # human-readable description of the event
            },
            ...
          ]
        }
    Logs are sorted most-recent-first. An IP with no logs in the window
    (known or entirely unrecognized) is NOT an error: it returns count=0
    and logs=[].
    """
    return data.query_logs(src_ip, hours)


@mcp.tool()
def lookup_cve(cve_id: str) -> dict:
    """Look up a CVE vulnerability record by its ID.

    NOTE: This dataset is entirely SYNTHETIC (invented for testing) and
    does not correspond to real-world CVE records.

    Args:
        cve_id: The CVE identifier to look up, e.g. "CVE-2024-90001".

    Returns exactly this JSON shape:
        {
          "cve_id": str,                    # normalized (uppercase) CVE id
          "found": bool,                    # true if this CVE exists in the dataset
          "severity": str | null,           # one of LOW, MEDIUM, HIGH, CRITICAL
          "cvss_score": float | null,       # 0.0-10.0
          "description": str | null,
          "affected_products": list[str],
          "published": str | null,          # "YYYY-MM-DD"
          "synthetic": true                 # always true; data is fabricated
        }

    A CVE ID not present in the dataset is NOT an error: it returns
    found=false with severity/cvss_score/description/published set to
    null and affected_products=[].
    """
    return data.lookup_cve(cve_id)


@mcp.tool()
def check_domain_reputation(domain: str) -> dict:
    """Look up threat-intelligence reputation data for a single domain.

    Args:
        domain: The domain name to look up, e.g. "cdn-analytics-node7.info".

    Returns exactly this JSON shape:
        {
          "domain": str,                    # echoes the input domain
          "malicious": bool,                # true if any source flags it malicious
          "score": int,                     # 0-100 risk score, higher = worse
          "category": str,                  # one of: malware, phishing, c2,
                                             #         suspicious, benign, unknown
          "sources_flagging": list[str],    # e.g. ["VirusTotal", "PhishTankSynthetic"]
          "first_seen": str | null          # "YYYY-MM-DD", or null if unknown
        }

    A domain not present in the dataset is NOT an error: it returns
    malicious=false, score=0, category="unknown", sources_flagging=[],
    first_seen=null.
    """
    return data.check_domain_reputation(domain)


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
